### ISSUE TITLE
Clojure implementation is inconsistent with hy, leaves a lot of perf on the table.

### ISSUE THREAD

**Issue by joinr** [ttsiodras/HexSpeak#1]
hylang version differs in a couple of areas that appeal to the microbench, clojure version leaves a lot of performance on the table, primarily due to excessive hashing compared to hy without much benefit due to the small size of the benchmark input.

1 - use unboxed math, which can mostly be detected with  `(set! *unchecked-math* :warn-on-boxed)`

2 - hylang implementation does not use a hashmap for the words-per-length and opts instead for a pre-allocated python list/array/vector to achieve hashless indexing of int->word list.  Clojure variant migrated to a vector instead of the persistent hashmap yielded by group-by provides similar performance benefits by eliminating relatively expensive hashing.

3 - hylang implementation does not use a hashset for the used-words var, resulting in concatenated word lists that are used as sets with linear scanning.  At a first glance this seems like folly since we could be dealing with many words based on user input; however the cited benchmark only ends up with used-words that are 5 or 6 words deep IIRC.  Changing clojure implementation to use a list for cheap conj and similar linear scanning yields similar performance improvement for this specific bench.

4 - no need to use atoms or volatiles when code is refactored to reduce.  a single primitive long is passed around.  Internal reduce over vectors instead of first/rest recursion implementation on generic seqs is typically much faster for iterative ops as well; bench yields some gains here.

https://gist.github.com/joinr/151328b75de954fd5d29169ddea9b838

I get between 2.5-2.66x improvement over the baseline on my end, yielding the same wordcounts for both.  The linked gist walks through annotated changes yielding the final implementation.  It is possible there are additional yields to be found by deviating from the reference implementations / algorithms, but I have not explored them in favor of keeping like comparisons and focusing on low-hanging fruit.

**Comment by ttsiodras** [comment]
Thanks, Tom! Interesting stuff - currently wrestling with real-life, but will review your feedback eventually. Cheers.
